export const cacheTags = {
  SALES_AI_LEADS: 'SALES_AI_LEADS',
  SALES_AI_LEAD_MESSAGES: 'SALES_AI_LEAD_MESSAGES',
  SALES_AI_PROMPTS: 'SALES_AI_PROMPTS',
  SALES_AI_PROMPT_INFO: 'SALES_AI_PROMPT_INFO',
};
